services:
  ctv-backend:
    build: ./packages/ctv-backend
    image: ctv-backend
    ports:
      - "3000:3000"
    restart: unless-stopped

  ctv-frontend:
    build: ./packages/ctv-frontend
    image: ctv-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - ctv-backend

  ctv-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ctv_user
      POSTGRES_PASSWORD: ctv_pass
      POSTGRES_DB: ctv_db
    ports:
      - "5432:5432"
    volumes:
      - ctv_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  ctv_postgres_data: